baseURL = 'http://assets.hdyar.com/'
languageCode = 'en-us'
mainSection = ['blog', 'docs']
title = 'Hunters Asset Collection'
subtitle = "Sub title of the site"
search = "duckduckgo"
assetDir = "/assets"
[Params]
mainSections = ['materials','models','sampleprojects']
