baseURL = 'https://assets.hdyar.com/'
languageCode = 'en-us'
title = 'Hunters Asset Collection'
search = "duckduckgo"
assetDir = "/assets"
[Params]
mainSections = ['materials','models','sampleprojects']
